using AiChatApp.Services;
using AiChatApp.Data;
using AiChatApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AiChatApp.Endpoints;

public static class SkillEndpoints
{
    public static void MapSkillEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/skills").RequireAuthorization();

        group.MapGet("/", async (SkillManagerService skillManager, ClaimsPrincipal user, [FromQuery] int? page, [FromQuery] int? pageSize) => {
            var userId = int.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!);
            var p = page ?? 1;
            var ps = pageSize ?? 20;
            var allSkills = await skillManager.GetAllSkillsAsync(userId);
            var paged = allSkills.Skip((p - 1) * ps).Take(ps + 1).ToList();

            if (!allSkills.Any() && p == 1)
                return Results.Content("<div class='text-center py-10 opacity-40'>No skills defined yet.</div>", "text/html");

            var hasMore = paged.Count > ps;
            var skills = paged.Take(ps).ToList();

            return Results.Content(string.Concat(skills.Select((s, index) => {
                var systemBadge = s.IsSystem ? "<span class='badge badge-neutral badge-xs mb-1'>System</span>" : "<span class='badge badge-primary badge-xs mb-1'>User</span>";
                var isLast = index == skills.Count - 1 && hasMore;
                var scrollAttr = isLast ? $"hx-get='/api/skills?page={p + 1}&pageSize={ps}' hx-trigger='revealed' hx-swap='afterend'" : "";
                return $@"
                <div class='flex flex-col p-3 bg-base-200 rounded-lg group' {scrollAttr}>
                    <div class='items-start justify-between flex'>
                        <div class='flex-1'>
                            {systemBadge}
                            <div class='font-bold text-sm'>{s.DisplayName}</div>
                            <div class='text-[10px] opacity-60 mb-2'>{s.Description}</div>
                            <textarea class='textarea textarea-bordered textarea-xs w-full h-24 font-mono text-[10px] bg-base-300'
                                      id='prompt-{s.Name}' readonly>{s.Prompt}</textarea>
                        </div>
                        <div class='flex flex-col items-end gap-2 ml-2'>
                            <button onclick='editSkillPrompt(""{s.Name}"")' class='btn btn-ghost btn-xs text-primary' id='btn-edit-{s.Name}'>Edit</button>
                            <button onclick='saveSkillPrompt(""{s.Name}"", {s.IsSystem.ToString().ToLower()})' class='btn btn-primary btn-xs hidden' id='btn-save-{s.Name}'>Save</button>
                            {(!s.IsSystem ? $@"<button hx-delete='/api/skills/{s.Name}' hx-target='closest div' hx-swap='outerHTML'
                                    class='btn btn-ghost btn-xs text-error opacity-0 group-hover:opacity-100'>Delete</button>" : "")}
                        </div>
                    </div>
                </div>";
            })), "text/html");
        });

        group.MapPost("/save", async (HttpContext context, ClaimsPrincipal user, SkillManagerService skillManager) => {
            var userId = int.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!);
            var form = await context.Request.ReadFormAsync();
            var name = form["name"].ToString();
            var prompt = form["prompt"].ToString();
            var isSystem = form["isSystem"].ToString() == "true";
            await skillManager.SaveSkillAsync(name, prompt, userId, isSystem);
            return Results.Ok();
        }).DisableAntiforgery();

        group.MapDelete("/{name}", (string name, ClaimsPrincipal user, SkillManagerService skillManager) => {
            var userId = int.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!);
            skillManager.DeleteSkill(name, userId, isSystem: false);
            return Results.Ok();
        });

        // --- Multi-AI Evolution Hub Endpoints ---

        group.MapGet("/evolution", async (ClaimsPrincipal user, AppDbContext db) => {
            var userId = int.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!);
            var pending = await db.Skills
                .Where(s => s.UserId == userId && s.IsAutoGenerated && !s.IsApproved)
                .ToListAsync();

            if (!pending.Any())
            {
                return Results.Content(@"
                    <div class='flex flex-col items-center justify-center p-8 bg-base-200/50 rounded-2xl border border-dashed border-base-300 text-center w-full'>
                        <div class='text-4xl mb-2'>🌱</div>
                        <div class='font-semibold text-sm opacity-80'>暂无待审批的进化提案</div>
                        <div class='text-xs opacity-50 mt-1 max-w-sm'>
                            系统会在您获得高分评价的 Agent 步骤中自动提取，或者您可以点击上方按钮“触发多 AI 评议”来主动分析最近的会话模式。
                        </div>
                    </div>", "text/html");
            }

            var html = string.Concat(pending.Select(s => $@"
                <div class='bg-base-200 border border-base-300 rounded-2xl p-5 shadow-sm hover:shadow-md transition-all duration-300 group flex flex-col gap-3 relative overflow-hidden' id='evo-card-{s.Id}'>
                    <div class='absolute top-0 right-0 w-24 h-24 bg-gradient-to-br from-primary/10 to-secondary/10 rounded-bl-full pointer-events-none'></div>
                    <style>
                    @keyframes fadeOut {{
                        to {{ opacity: 0; height: 0; padding: 0; margin: 0; border: none; display: none; }}
                    }}
                    .animate-fade-out {{
                        animation: fadeOut 1s forwards;
                        animation-delay: 1.5s;
                    }}
                    </style>
                    <div class='flex justify-between items-start z-10'>
                        <div>
                            <span class='badge badge-secondary badge-xs gap-1 font-semibold py-2 px-2'>
                                <span class='w-1.5 h-1.5 rounded-full bg-success animate-pulse'></span>
                                AI Council Proposed
                            </span>
                            <h3 class='font-bold text-base mt-2 flex items-center gap-2 text-primary'>
                                {s.Name}
                            </h3>
                            <div class='text-xs opacity-60 mt-1'>
                                触发词: <span class='badge badge-ghost badge-sm font-mono'>{s.TriggerKeywords}</span>
                            </div>
                        </div>
                    </div>
                    <div class='flex-1 z-10'>
                        <div class='text-xs font-semibold opacity-70 mb-1'>提取的系统指令:</div>
                        <textarea class='textarea textarea-bordered textarea-sm w-full h-28 font-mono text-[11px] bg-base-300/80 leading-relaxed resize-none' readonly>{s.Description}</textarea>
                    </div>
                    <div class='flex gap-2 justify-end mt-2 z-10'>
                        <button hx-post='/api/skills/evolution/{s.Id}/reject' hx-target='#evo-card-{s.Id}' hx-swap='outerHTML' class='btn btn-ghost btn-sm text-error'>
                            ✕ 拒绝
                        </button>
                        <button hx-post='/api/skills/evolution/{s.Id}/approve' hx-target='#evo-card-{s.Id}' hx-swap='outerHTML' class='btn btn-primary btn-sm px-4'>
                            ✓ 承认并启用
                        </button>
                    </div>
                </div>
            "));

            return Results.Content(html, "text/html");
        });

        group.MapPost("/evolution/{id:int}/approve", async (int id, ClaimsPrincipal user, AppDbContext db, SkillManagerService skillManager) => {
            var userId = int.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!);
            var skill = await db.Skills.FindAsync(id);
            if (skill == null || skill.UserId != userId) return Results.NotFound();

            skill.IsApproved = true;
            skill.IsEnabled = true;
            await db.SaveChangesAsync();

            // 同时写入本地文件系统以在常规列表显示
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("---");
            sb.AppendLine($"name: {skill.Name}");
            sb.AppendLine($"description: Triggered by: {skill.TriggerKeywords}");
            sb.AppendLine("---");
            sb.AppendLine(skill.Description);
            await skillManager.SaveSkillAsync(skill.Name, sb.ToString(), userId, isSystem: false);

            return Results.Content($@"
                <div class='alert alert-success shadow-sm py-3 animate-fade-out w-full'>
                    <svg xmlns='http://www.w3.org/2000/svg' class='stroke-current shrink-0 h-6 w-6' fill='none' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z' /></svg>
                    <span>技能 ""{skill.Name}"" 已启用并同步到常规技能库！</span>
                </div>", "text/html");
        }).DisableAntiforgery();

        group.MapPost("/evolution/{id:int}/reject", async (int id, ClaimsPrincipal user, AppDbContext db) => {
            var userId = int.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!);
            var skill = await db.Skills.FindAsync(id);
            if (skill == null || skill.UserId != userId) return Results.NotFound();

            db.Skills.Remove(skill);
            await db.SaveChangesAsync();

            return Results.Content(@"
                <div class='alert alert-warning shadow-sm py-3 opacity-60 animate-fade-out w-full'>
                    <span>已拒绝该提案。</span>
                </div>", "text/html");
        }).DisableAntiforgery();

        group.MapPost("/evolution/deliberate", async (ClaimsPrincipal user, AppDbContext db, MultiAiCouncilService council) => {
            var userId = int.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!);
            
            // 1. 获取该用户最近的会话内容作为评议语料
            var sessionIds = await db.ChatSessions
                .Where(s => s.UserId == userId)
                .Select(s => s.Id)
                .ToListAsync();

            var recentMessages = await db.Messages
                .Where(m => sessionIds.Contains(m.ChatSessionId))
                .OrderByDescending(m => m.Timestamp)
                .Take(30)
                .ToListAsync();

            if (!recentMessages.Any())
            {
                return Results.Content("<div class='alert alert-warning shadow-sm w-full'><svg xmlns='http://www.w3.org/2000/svg' class='stroke-current shrink-0 h-6 w-6' fill='none' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z' /></svg><span>无法评议：当前没有足够的聊天历史。请多聊几句后再试。</span></div>", "text/html");
            }

            recentMessages.Reverse(); // 按时间正序
            var batchText = string.Join("\n", recentMessages.Select(m => $"{(m.IsAi ? "AI" : "User")}: {m.Content}"));

            // 2. 调用评议服务运行多 AI (Gemini + Claude)
            var proposals = await council.DeliberateAsync(batchText, userId);

            if (proposals == null || !proposals.Any())
            {
                return Results.Content("<div class='alert alert-info shadow-sm w-full'><svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' class='stroke-current shrink-0 w-6 h-6'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z'></path></svg><span>AI 评议已结束，未发现明确可提取的新进化技能模式。</span></div>", "text/html");
            }

            int createdCount = 0;
            foreach (var p in proposals)
            {
                if (p.Type != "skill" && p.Type != "skill_heal") continue;

                // 重复校验
                var existing = await db.Skills.FirstOrDefaultAsync(s => s.UserId == userId && s.Name.ToLower() == p.Title.ToLower());
                if (existing != null)
                {
                    if (existing.IsAutoGenerated && !existing.IsApproved)
                    {
                        // 尚未审批的提案直接覆盖
                        existing.Description = p.Content;
                        existing.TriggerKeywords = p.TriggerKeywords != null ? string.Join(", ", p.TriggerKeywords) : "";
                        existing.LastUsedAt = DateTime.UtcNow;
                    }
                    else if (p.Type == "skill_heal" || (existing.UseCount >= 3 && ((float)existing.SuccessCount / existing.UseCount) < 0.60f))
                    {
                        // 低成功率技能的自愈：覆盖、设为待批准、重置指标
                        existing.Description = p.Content;
                        existing.TriggerKeywords = p.TriggerKeywords != null ? string.Join(", ", p.TriggerKeywords) : "";
                        existing.IsApproved = false;
                        existing.IsEnabled = true;
                        existing.SuccessCount = 1;
                        existing.UseCount = 0;
                        existing.LastUsedAt = DateTime.UtcNow;
                        createdCount++;
                    }
                    continue;
                }

                var newSkill = new Skill
                {
                    UserId = userId,
                    Name = p.Title,
                    Description = p.Content,
                    TriggerKeywords = p.TriggerKeywords != null ? string.Join(", ", p.TriggerKeywords) : "",
                    IsEnabled = true,
                    IsAutoGenerated = true,
                    IsApproved = false,
                    UseCount = 0,
                    SuccessCount = 1,
                    LastUsedAt = DateTime.UtcNow
                };
                db.Skills.Add(newSkill);
                createdCount++;
            }

            if (createdCount > 0)
            {
                await db.SaveChangesAsync();
            }

            return Results.Content($@"
                <div class='alert alert-success shadow-sm w-full' hx-get='/api/skills/evolution' hx-trigger='load' hx-target='#evolution-list'>
                    <svg xmlns='http://www.w3.org/2000/svg' class='stroke-current shrink-0 h-6 w-6' fill='none' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z' /></svg>
                    <span>评议成功！多 AI (Gemini + Claude) 合作提议并精炼了 {createdCount} 个新的进化技能，已加入下方列表中。</span>
                </div>", "text/html");
        }).DisableAntiforgery();
    }
}
