namespace AiChatApp.Models;

public class Skill
{
    public int Id { get; set; }
    public int UserId { get; set; }                         // ユーザースコープ（グローバルから変更）
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string ExampleInput { get; set; } = string.Empty;
    public string TriggerKeywords { get; set; } = string.Empty; // 発火キーワード（カンマ区切り）。空の場合は常に有効
    public bool IsEnabled { get; set; } = true;
    public string? BoundAgentRole { get; set; }             // null=全エージェント, "Executor"=Executorのみ

    // --- Hermes Learning Loop Fields ---
    public int UseCount { get; set; } = 0;           // 使用回数
    public int SuccessCount { get; set; } = 0;        // 成功回数（Reviewerが高評価した回数）
    public DateTime? LastUsedAt { get; set; }
    public bool IsAutoGenerated { get; set; } = false; // AIが自動生成したか
    public bool IsApproved { get; set; } = true;      // ユーザーが承認済みか
    public string? SourceInteractionId { get; set; }  // 元になった会話ID（MessageId等）

    public User? User { get; set; }
}
