using AiChatApp.Data;
using AiChatApp.Models;
using Microsoft.EntityFrameworkCore;

namespace AiChatApp.Services;

public class MemorySearchService
{
    private readonly AppDbContext _db;
    private readonly MemoryFileService _fileService;
    private readonly MemoryGraphService _graphService;

    public MemorySearchService(AppDbContext db, MemoryFileService fileService, MemoryGraphService graphService)
    {
        _db = db;
        _fileService = fileService;
        _graphService = graphService;
    }

    /// <summary>プロンプトに関連する記憶をmdファイルから検索する。キーワード検索 + グラフ拡張の2段階。</summary>
    public async Task<List<LongTermMemory>> SearchAsync(string prompt, int userId, int maxResults = 5)
    {
        // 1. キーワードベースの広域検索 (Top 15)
        var initialResults = await _fileService.SearchAsync(prompt, userId, 15);

        // 2. グラフ拡張 (Knowledge Graph expansion)
        _graphService.BuildGraph(userId);
        var expandedResults = new List<LongTermMemory>(initialResults);
        var seenFiles = initialResults.Select(m => m.SourceFile).ToHashSet();

        foreach (var mem in initialResults)
        {
            var related = _graphService.GetRelatedMemories(mem, userId, limit: 2);
            foreach (var r in related)
            {
                if (r.SourceFile != null && !seenFiles.Contains(r.SourceFile))
                {
                    expandedResults.Add(r);
                    seenFiles.Add(r.SourceFile);
                }
            }
        }

        return expandedResults.Take(maxResults).ToList();
    }

    /// <summary>有効スキルをトリガーキーワードで検索する（DB）。</summary>
    public async Task<List<Skill>> SearchSkillsAsync(string prompt, int userId, string? agentRole = null)
    {
        var skills = await _db.Skills
            .Where(s => s.UserId == userId && s.IsEnabled && (!s.IsAutoGenerated || s.IsApproved))
            .ToListAsync();

        return skills.Where(s =>
        {
            if (s.BoundAgentRole != null && s.BoundAgentRole != agentRole) return false;
            if (string.IsNullOrWhiteSpace(s.TriggerKeywords)) return true;

            var keywords = s.TriggerKeywords
                .Split(',', StringSplitOptions.RemoveEmptyEntries)
                .Select(k => k.Trim());

            return keywords.Any(k => prompt.Contains(k, StringComparison.OrdinalIgnoreCase));
        }).ToList();
    }
}
