using AiChatApp.Data;
using AiChatApp.Models;
using Microsoft.EntityFrameworkCore;

namespace AiChatApp.Services;

public class MemorySearchService
{
    private readonly AppDbContext _db;
    private readonly MemoryFileService _fileService;
    private readonly MemoryGraphService _graphService;

    public MemorySearchService(AppDbContext db, MemoryFileService fileService, MemoryGraphService graphService)
    {
        _db = db;
        _fileService = fileService;
        _graphService = graphService;
    }

    /// <summary>プロンプトに関連する記憶をmdファイルから検索する。キーワード検索 + 必要時のみグラフ拡張。</summary>
    public async Task<List<LongTermMemory>> SearchAsync(string prompt, int userId, int maxResults = 5)
    {
        // 1. キーワードベースの検索（目標数だけ取得）
        var initialResults = await _fileService.SearchAsync(prompt, userId, maxResults);

        // 2. 結果が目標数に満たない場合のみグラフ拡張
        if (initialResults.Count >= maxResults)
            return initialResults;
// 2. 結果が目標数に満たない場合のみグラフ拡張
await _graphService.BuildGraphAsync(userId);
var expandedResults = new List<LongTermMemory>(initialResults);
var seenFiles = initialResults.Select(m => m.SourceFile).ToHashSet();

foreach (var mem in initialResults)
{
    if (expandedResults.Count >= maxResults) break;
    var related = await _graphService.GetRelatedMemoriesAsync(mem, userId, limit: 2);
    foreach (var r in related)

            {
                if (expandedResults.Count >= maxResults) break;
                if (r.SourceFile != null && !seenFiles.Contains(r.SourceFile))
                {
                    expandedResults.Add(r);
                    seenFiles.Add(r.SourceFile);
                }
            }
        }

        return expandedResults;
    }

    /// <summary>有効スキルをトリガーキーワードで検索する（DB）。</summary>
    public async Task<List<Skill>> SearchSkillsAsync(string prompt, int userId, string? agentRole = null)
    {
        var query = _db.Skills
            .Where(s => s.UserId == userId && s.IsEnabled && (!s.IsAutoGenerated || s.IsApproved));

        if (agentRole != null)
            query = query.Where(s => s.BoundAgentRole == null || s.BoundAgentRole == agentRole);
        else
            query = query.Where(s => s.BoundAgentRole == null);

        var skills = await query.ToListAsync();

        return skills.Where(s =>
        {
            if (string.IsNullOrWhiteSpace(s.TriggerKeywords)) return true;
            var keywords = s.TriggerKeywords
                .Split(',', StringSplitOptions.RemoveEmptyEntries)
                .Select(k => k.Trim());

            return keywords.Any(k => prompt.Contains(k, StringComparison.OrdinalIgnoreCase));
        }).ToList();
    }
}
