using AiChatApp.Data;
using AiChatApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace AiChatApp.Services;

public class MemorySearchService
{
    private readonly AppDbContext _db;
    private readonly MemoryFileService _fileService;
    private readonly MemoryGraphService _graphService;
    private readonly IServiceProvider _serviceProvider;

    public MemorySearchService(AppDbContext db, MemoryFileService fileService, MemoryGraphService graphService, IServiceProvider serviceProvider)
    {
        _db = db;
        _fileService = fileService;
        _graphService = graphService;
        _serviceProvider = serviceProvider;
    }

    /// <summary>プロンプトに関連する記憶をmdファイルから検索する。多段検索（キーワード + グラフ拡張 + セマンティック再ランク）を行う。</summary>
    public async Task<List<LongTermMemory>> SearchAsync(string prompt, int userId, int maxResults = 5)
    {
        // 1. キーワードベースの広域検索 (Top 15)
        var initialResults = await _fileService.SearchAsync(prompt, userId, 15);
        
        // 2. グラフ拡張 (Knowledge Graph expansion)
        _graphService.BuildGraph(userId);
        var expandedResults = new List<LongTermMemory>(initialResults);
        var seenFiles = initialResults.Select(m => m.SourceFile).ToHashSet();

        foreach (var mem in initialResults)
        {
            var related = _graphService.GetRelatedMemories(mem, userId, limit: 2);
            foreach (var r in related)
            {
                if (r.SourceFile != null && !seenFiles.Contains(r.SourceFile))
                {
                    expandedResults.Add(r);
                    seenFiles.Add(r.SourceFile);
                }
            }
        }

        if (expandedResults.Count <= maxResults) return expandedResults;

        // 3. セマンティック再ランク (AIによる関連性評価)
        try
        {
            var aiService = _serviceProvider.GetRequiredService<AiService>();
            
            var memoryList = string.Join("\n", expandedResults.Select((m, i) => $"ID:{i} | Tags:{m.Tags} | Content:{m.Content}"));
            
            string rankPrompt = $"""
                Identify the most relevant memories for the user's prompt from the list below. 
                Consider both semantic relevance and logical connection.
                Return only the IDs of the top {maxResults} memories as a comma-separated list, in order of relevance.
                
                USER PROMPT: {prompt}
                
                MEMORIES:
                {memoryList}
                
                OUTPUT FORMAT: 0,2,5...
                """;

            string result = await aiService.ExecuteCliDirectAsync(rankPrompt, aiService.DefaultProvider);
            var idStrings = result.Split(new[] { ',', ' ', '\n' }, StringSplitOptions.RemoveEmptyEntries);
            
            var reranked = new List<LongTermMemory>();
            foreach (var idStr in idStrings)
            {
                if (int.TryParse(idStr.Trim(), out int index) && index >= 0 && index < expandedResults.Count)
                {
                    reranked.Add(expandedResults[index]);
                    if (reranked.Count >= maxResults) break;
                }
            }

            return reranked.Any() ? reranked : expandedResults.Take(maxResults).ToList();
        }
        catch
        {
            // フォールバック: 単純な上位取得
            return expandedResults.Take(maxResults).ToList();
        }
    }

    /// <summary>有効スキルをトリガーキーワードで検索する（DB）。</summary>
    public async Task<List<Skill>> SearchSkillsAsync(string prompt, int userId, string? agentRole = null)
    {
        var skills = await _db.Skills
            .Where(s => s.UserId == userId && s.IsEnabled && (!s.IsAutoGenerated || s.IsApproved))
            .ToListAsync();

        return skills.Where(s =>
        {
            if (s.BoundAgentRole != null && s.BoundAgentRole != agentRole) return false;
            if (string.IsNullOrWhiteSpace(s.TriggerKeywords)) return true;

            var keywords = s.TriggerKeywords
                .Split(',', StringSplitOptions.RemoveEmptyEntries)
                .Select(k => k.Trim());

            return keywords.Any(k => prompt.Contains(k, StringComparison.OrdinalIgnoreCase));
        }).ToList();
    }
}
