using System.Text.Json;
using AiChatApp.Data;
using AiChatApp.Models;
using Microsoft.EntityFrameworkCore;

namespace AiChatApp.Services;

public class SkillLearningService
{
    private readonly AppDbContext _db;
    private readonly AiService _aiService;

    public SkillLearningService(AppDbContext db, AiService aiService)
    {
        _db = db;
        _aiService = aiService;
    }

    /// <summary>
    /// タスク完了後に呼び出す。反省→スキル候補抽出→DB保存。
    /// </summary>
    public async Task LearnFromInteractionAsync(
        string task, string finalOutput, List<AgentStep> steps, int userId)
    {
        try
        {
            var proposals = await ReflectAndProposeAsync(task, finalOutput, steps);
            
            foreach (var prop in proposals)
            {
                // 既存の同名スキルがないかチェック
                var exists = await _db.Skills.AnyAsync(s => s.UserId == userId && s.Name == prop.Name);
                if (exists) continue;

                var skill = new Skill
                {
                    UserId = userId,
                    Name = prop.Name,
                    Description = prop.Description,
                    TriggerKeywords = prop.TriggerKeywords,
                    BoundAgentRole = prop.BoundAgentRole,
                    IsAutoGenerated = true,
                    IsApproved = false, // ユーザーの承認待ち
                    IsEnabled = true
                };

                _db.Skills.Add(skill);
            }

            await _db.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            // 非同期で実行されることが多いため、エラーログを出力（ここではConsole）
            Console.WriteLine($"[SkillLearningService] Error: {ex.Message}");
        }
    }

    /// <summary>
    /// スキル有効性の評価を更新する
    /// </summary>
    public async Task UpdateSkillMetricsAsync(int skillId, bool wasSuccessful)
    {
        var skill = await _db.Skills.FindAsync(skillId);
        if (skill == null) return;

        skill.UseCount++;
        if (wasSuccessful) skill.SuccessCount++;
        skill.LastUsedAt = DateTime.UtcNow;

        await _db.SaveChangesAsync();
    }

    private async Task<List<SkillProposal>> ReflectAndProposeAsync(
        string task, string outcome, List<AgentStep> steps)
    {
        string prompt = $$"""
            あなたはスキル抽出の専門家です。
            以下のタスクの実行記録を分析し、将来の類似タスクで再利用できる
            「スキルパターン」を抽出してください。

            タスク: {{task}}
            最終結果: {{outcome}}
            エージェント実行ログ:
            {{string.Join("\n", steps.Select(s => $"[{s.Role}]: {s.Output.Substring(0, Math.Min(200, s.Output.Length))}..."))}}

            以下のJSON形式のみで回答してください:
            [
              {
                "name": "スキル名（英語CamelCase）",
                "description": "このスキルが何をするかの説明（AIへの指示として書く）",
                "triggerKeywords": "発火キーワード（カンマ区切り）",
                "boundAgentRole": "Executor|Reviewer|null",
                "rationale": "このスキルが必要な理由（1文）"
              }
            ]
            抽出できない場合は [] を返してください。
            """;

        string response = await _aiService.ExecuteCliDirectAsync(prompt, "gemini");
        string json = ExtractJson(response);

        try
        {
            return JsonSerializer.Deserialize<List<SkillProposal>>(json, new JsonSerializerOptions 
            { 
                PropertyNameCaseInsensitive = true 
            }) ?? new List<SkillProposal>();
        }
        catch
        {
            return new List<SkillProposal>();
        }
    }

    private static string ExtractJson(string text)
    {
        int start = text.IndexOf('[');
        int end = text.LastIndexOf(']');
        if (start >= 0 && end > start) return text[start..(end + 1)];
        return "[]";
    }
}

public record SkillProposal(
    string Name,
    string Description,
    string TriggerKeywords,
    string? BoundAgentRole,
    string Rationale
);
